In [1]:
import pandas as pd

In [ ]:
extracted_data = pd.read_csv("data_files/data_1.csv")
project_metadata= pd.read_csv("data_files/project_metadata.csv")
print("Project Metadata Columns:", project_metadata.columns.tolist())
print("\nExtracted Data Columns:", extracted_data.columns.tolist())

Project Metadata Columns: ['No.', 'Country', 'Project ID', 'Project Name', 'Type', 'SE', 'Region', 'Call For Proposal', 'Status', 'SE Approval Date', 'First disbursement date of GAFSP funds', 'Additional Financing Approval Date 1', 'Project Closing Expected Date', 'Project Closing Date', 'Additonal Funding Request Amount', 'Revised Funding Request Amount', 'Remark', 'No. of PADs', 'Link']

Extracted Data Columns: ['source_file', 'PROJ_DEV_OBJECTIVE_DESC', 'LEAD_GP_NAME', 'CMT_AMT', 'Climate Financing (%)', 'Adaptation (%)', 'Mitigation (%)', 'PriorActions', 'Indicators', 'Components', 'DLI_DLR']

In [3]:
extracted_data['Project ID'] = extracted_data['source_file'].str.replace('.pdf', '', regex=False)
extracted_data = extracted_data.drop('source_file', axis=1)
extracted_data

,PROJ_DEV_OBJECTIVE_DESC,LEAD_GP_NAME,CMT_AMT,Climate Financing (%),Adaptation (%),Mitigation (%),PriorActions,Indicators,Components,DLI_DLR,Project ID
0,The Project to Support Food Production and Bui...,Agriculture and Rural Development,USD 27.13 million,Not Available,Not Available,Not Available,Not Available,ERR (baseline scenario) | IRR (baseline scenar...,Support for Rural Infrastructure | Development...,Not Available,AFDB-BJ-P
1,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,AFDB-KE-P
2,The Koulikoro Region Food and Nutrition Securi...,OSAN,USD 47.21 million,Not Available,Not Available,Not Available,"Signature of the loan and grant agreements, fu...",National poverty rate - Target: 34.5% in 2024 ...,A- Infrastructure Development (A1 Irrigation d...,Not Available,AFDB-ML-P
3,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,FAO-KE-P
4,The Smallholder Commercialisation Programme (S...,Programme Management Department,USD 50 million,Not Available,Not Available,Not Available,Not Available,Agricultural sector growth from 4 percent to 7...,Component 1: Smallholder agriculture commercia...,Not Available,GAFSP00023

In [4]:
full_data = extracted_data.merge(project_metadata, on='Project ID', how='left')

In [5]:
full_data

,PROJ_DEV_OBJECTIVE_DESC,LEAD_GP_NAME,CMT_AMT,Climate Financing (%),Adaptation (%),Mitigation (%),PriorActions,Indicators,Components,DLI_DLR,...,SE Approval Date,First disbursement date of GAFSP funds,Additional Financing Approval Date 1,Project Closing Expected Date,Project Closing Date,Additonal Funding Request Amount,Revised Funding Request Amount,Remark,No. of PADs,Link
0,The Project to Support Food Production and Bui...,Agriculture and Rural Development,USD 27.13 million,Not Available,Not Available,Not Available,Not Available,ERR (baseline scenario) | IRR (baseline scenar...,Support for Rural Infrastructure | Development...,Not Available,...,10/07/2015,06/16/2016,NaN,NaN,06/30/2023,NaN,24.00,PAD Available,1.0,NaN
1,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,...,11/18/2015,07/01/2016,NaN,NaN,06/30/2023,NaN,22.80,PAD Available,1.0,NaN
2,The Koulikoro Region Food and Nutrition Securi...,OSAN,USD 47.21 million,Not Available,Not Available,Not Available,"Signature of the loan and grant agreements, fu...",National poverty rate - Target: 34.5% in 2024 ...,A- Infrastructure Development (A1 Irrigation d...,Not Available,...,09/17/2014,03/05/2015,NaN,NaN,12/31/2021,NaN,37.21,PAD Available,1.0,NaN
3,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,...,09/01/2015,01/19/2017,NaN,NaN,06/30/2022,NaN,1.20,PAD Available,1.0,NaN
4,The Smallholder Commercialisation Programme (S...,Programme Management Department,USD 50 million,Not Available,Not Available,Not Available,Not Available,Agricultural sector growth from 4 percent to 7...,Component 1: Smallholder agriculture commercia...,Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Create a copy of PROJ_DEV_OBJECTIVE_DESC in a new column
full_data['PROJ_OBJECTIVE_TEXT'] = full_data['PROJ_DEV_OBJECTIVE_DESC']

# Convert SE Approval Date to year (YYYY) format
full_data['SE Approval Date'] = pd.to_datetime(full_data['SE Approval Date'], errors='coerce').dt.year

# Rename the columns
full_data = full_data.rename(columns={
    "Project ID": "PROJ_ID",
    "Project Name": "PROJ_DISPLAY_NAME",
    "SE Approval Date": "PROJ_APPRVL_FY",
    "Status": "PROJ_STAT_NAME",
    "Country": "CNTRY_SHORT_NAME",
    "Type": "LNDNG_INSTR_LONG_NAME"
})

full_data

,PROJ_DEV_OBJECTIVE_DESC,LEAD_GP_NAME,CMT_AMT,Climate Financing (%),Adaptation (%),Mitigation (%),PriorActions,Indicators,Components,DLI_DLR,...,First disbursement date of GAFSP funds,Additional Financing Approval Date 1,Project Closing Expected Date,Project Closing Date,Additonal Funding Request Amount,Revised Funding Request Amount,Remark,No. of PADs,Link,PROJ_OBJECTIVE_TEXT
0,The Project to Support Food Production and Bui...,Agriculture and Rural Development,USD 27.13 million,Not Available,Not Available,Not Available,Not Available,ERR (baseline scenario) | IRR (baseline scenar...,Support for Rural Infrastructure | Development...,Not Available,...,06/16/2016,NaN,NaN,06/30/2023,NaN,24.00,PAD Available,1.0,NaN,The Project to Support Food Production and Bui...
1,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,...,07/01/2016,NaN,NaN,06/30/2023,NaN,22.80,PAD Available,1.0,NaN,The Kenya Small Scale Irrigation and Value Add...
2,The Koulikoro Region Food and Nutrition Securi...,OSAN,USD 47.21 million,Not Available,Not Available,Not Available,"Signature of the loan and grant agreements, fu...",National poverty rate - Target: 34.5% in 2024 ...,A- Infrastructure Development (A1 Irrigation d...,Not Available,...,03/05/2015,NaN,NaN,12/31/2021,NaN,37.21,PAD Available,1.0,NaN,The Koulikoro Region Food and Nutrition Securi...
3,The Kenya Small Scale Irrigation and Value Add...,Water Resources,USD 70.684 million,Not Available,Not Available,Not Available,Not Available,"Economic Internal Rate of Return (EIRR), 28% a...",Enhanced Irrigation Infrastructures and Water ...,Not Available,...,01/19/2017,NaN,NaN,06/30/2022,NaN,1.20,PAD Available,1.0,NaN,The Kenya Small Scale Irrigation and Value Add...
4,The Smallholder Commercialisation Programme (S...,Programme Management Department,USD 50 million,Not Available,Not Available,Not Available,Not Available,Agricultural sector growth from 4 percent to 7...,Component 1: Smallholder agriculture commercia...,Not Available,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Smallholder Commercialisation Programme (S...

In [8]:
# Reorder columns with specified columns at the beginning
column_order = ["PROJ_ID", "PROJ_DISPLAY_NAME", "PROJ_APPRVL_FY", "PROJ_DEV_OBJECTIVE_DESC", 
                "PROJ_STAT_NAME", "CNTRY_SHORT_NAME", "LNDNG_INSTR_LONG_NAME", "LEAD_GP_NAME", 
                "CMT_AMT", "PROJ_OBJECTIVE_TEXT", "Region", "Climate Financing (%)", 
                "Adaptation (%)", "Mitigation (%)", "PriorActions", "Indicators", "Components", "DLI_DLR"]

# Get remaining columns not in the specified order
remaining_columns = [col for col in full_data.columns if col not in column_order]

# Combine and reorder
full_data = full_data[column_order + remaining_columns]

full_data

,PROJ_ID,PROJ_DISPLAY_NAME,PROJ_APPRVL_FY,PROJ_DEV_OBJECTIVE_DESC,PROJ_STAT_NAME,CNTRY_SHORT_NAME,LNDNG_INSTR_LONG_NAME,LEAD_GP_NAME,CMT_AMT,PROJ_OBJECTIVE_TEXT,...,Call For Proposal,First disbursement date of GAFSP funds,Additional Financing Approval Date 1,Project Closing Expected Date,Project Closing Date,Additonal Funding Request Amount,Revised Funding Request Amount,Remark,No. of PADs,Link
0,AFDB-BJ-P,Project to Support Food Production and Build R...,2015.0,The Project to Support Food Production and Bui...,Project Closed,Benin,Investment,Agriculture and Rural Development,USD 27.13 million,The Project to Support Food Production and Bui...,...,Third Call [2014],06/16/2016,NaN,NaN,06/30/2023,NaN,24.00,PAD Available,1.0,NaN
1,AFDB-KE-P,Kenya Small Scale Irrigation and Value Additio...,2015.0,The Kenya Small Scale Irrigation and Value Add...,Project Closed,Kenya,Investment,Water Resources,USD 70.684 million,The Kenya Small Scale Irrigation and Value Add...,...,Third Call [2014],07/01/2016,NaN,NaN,06/30/2023,NaN,22.80,PAD Available,1.0,NaN
2,AFDB-ML-P,Food and Nutrition Security Enhancement Projec...,2014.0,The Koulikoro Region Food and Nutrition Securi...,Project Closed,Mali,Investment,OSAN,USD 47.21 million,The Koulikoro Region Food and Nutrition Securi...,...,Third Call [2013],03/05/2015,NaN,NaN,12/31/2021,NaN,37.21,PAD Available,1.0,NaN
3,FAO-KE-P,Kenya Small Scale Irrigation and Value Additio...,2015.0,The Kenya Small Scale Irrigation and Value Add...,Project Closed,Kenya,Technical Assistance,Water Resources,USD 70.684 million,The Kenya Small Scale Irrigation and Value Add...,...,Third Call [2014],01/19/2017,NaN,NaN,06/30/2022,NaN,1.20,PAD Available,1.0,NaN
4,GAFSP00023,NaN,NaN,The Smallholder Commercialisation Programme (S...,NaN,NaN,NaN,Programme Management Department,USD 50 million,The Smallholder Commercialisation Programme (S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
hierarchy = pd.DataFrame([
    {"Hierarchy Name": "School", "Full Name": "School", "Keyword": "school"},
    {"Hierarchy Name": "HGSF", "Full Name": "home-grown school feeding", "Keyword": "school feeding"},
    {"Hierarchy Name": "HGSF", "Full Name": "home-grown school feeding", "Keyword": "school meals"},
    {"Hierarchy Name": "HGSF", "Full Name": "home-grown school feeding", "Keyword": "students"},
    {"Hierarchy Name": "HGSF", "Full Name": "home-grown school feeding", "Keyword": "pupils"},
    {"Hierarchy Name": "WFP", "Full Name": "World food programme", "Keyword": "school meals"},
    {"Hierarchy Name": "WFP", "Full Name": "World food programme", "Keyword": "school feeding"}
])

In [11]:
hierarchy

  Hierarchy Name                  Full Name         Keyword
0         School                     School          school
1           HGSF  home-grown school feeding  school feeding
2           HGSF  home-grown school feeding    school meals
3           HGSF  home-grown school feeding        students
4           HGSF  home-grown school feeding          pupils
5            WFP       World food programme    school meals
6            WFP       World food programme  school feeding

In [12]:
hierarchy.to_csv("hierarchy.csv", index=False)
full_data.to_csv("full_data.csv", index=False)